on:
  push:
  pull_request:
name: Test and release
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v7
      - uses: actions/cache@v6
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
      - run: go test -race ./...

  release:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs:
      - test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Bump the version on main push
        uses: hennejg/github-tag-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: "main"
